// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmjRHCNslBUjsg4EchmgjFgNnEKy6xJAw',
    appId: '1:73395870439:web:92364ae51f94d3158ae042',
    messagingSenderId: '73395870439',
    projectId: 'authentication-59f42',
    authDomain: 'authentication-59f42.firebaseapp.com',
    storageBucket: 'authentication-59f42.appspot.com',
    measurementId: 'G-04SFGD5B8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBywfmhOrvBp0izMXtn58Hbfdk70ydQhg0',
    appId: '1:73395870439:android:874d92f5b70cab758ae042',
    messagingSenderId: '73395870439',
    projectId: 'authentication-59f42',
    storageBucket: 'authentication-59f42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIdEyq2UPSmCR09Cfb6hT5ndvHAmRkqW8',
    appId: '1:73395870439:ios:4e56c0853c7c5c678ae042',
    messagingSenderId: '73395870439',
    projectId: 'authentication-59f42',
    storageBucket: 'authentication-59f42.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIdEyq2UPSmCR09Cfb6hT5ndvHAmRkqW8',
    appId: '1:73395870439:ios:59fc8e8ef6334c408ae042',
    messagingSenderId: '73395870439',
    projectId: 'authentication-59f42',
    storageBucket: 'authentication-59f42.appspot.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
